repos:
  - repo: https://github.com/datarootsio/databooks
    rev: 1.2.5
    hooks:
      - id: databooks-meta
        args: ["--cell-meta-keep=tags", "--nb-meta-keep=kernelspec"]  #, "--nb-meta-keep=language_info"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^data/
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^data/
      - id: mixed-line-ending
        exclude: ^data/
      - id: check-added-large-files
        args: ['--maxkb=9000']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: isort
        entry: python -m isort
        args: [--settings-path, ./pyproject.toml]
        language: system
        types: [python]
