repos:
  - repo: https://github.com/datarootsio/databooks
    rev: 1.2.5
    hooks:
      - id: databooks-meta
        args: ["--cell-meta-keep=tags", "--nb-meta-keep=kernelspec"]  #, "--nb-meta-keep=language_info"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^data/
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^data/
      - id: mixed-line-ending
        exclude: ^data/
      - id: check-added-large-files
        args: ['--maxkb=9000']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: isort
        entry: python -m isort
        args: [--settings-path, ./pyproject.toml]
        language: system
        types: [python]
  # - repo: https://github.com/pycqa/flake8.git
  #   rev: 3.9.2
  #   hooks:
  #   - id: flake8
  #     additional_dependencies: [flake8-print, "importlib-metadata<5.0.0"]
  #     args: [--config=setup.cfg]
  #     exclude: ^examples/
  # - repo: https://github.com/psf/black
  #   rev: 19.10b0
  #   hooks:
  #   - id: black
  #     language_version: python3
  #     additional_dependencies: ['click==8.0.4']
